var arr=[1,"nikhil","Male",true,100];
console.log(arr[1]);
arr.push(27);
console.log(arr);
arr.pop();
console.log(arr);
arr.unshift("Mr.");
console.log(arr);
arr.shift();
arr.splice(2,1);
console.log(arr);
arr.splice(2,0,"Human");
console.log(arr);